apiVersion: apps/v1
kind: Deployment
metadata:
  name: education
  labels:
    app: education
spec:
  replicas: 1
  selector:
    matchLabels:
      app: education
  template:
    metadata:
      labels:
        app: education
    spec:
      containers:
        - name: education
          image: username/education:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
          resources:
            requests:
              cpu: 200m
            limits:
              cpu: 500m